env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

task:
    name: aosp
    timeout_in: 260m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    download_ccache_background_script: # To download ccache in background
      - curl -o /tmp/ci/function https://raw.githubusercontent.com/qwry3657/cirrus/main/function
      - curl -o /tmp/ci/download_ccache https://raw.githubusercontent.com/qwry3657/cirrus/main/download_ccache
      - bash download_ccache # Ccache download script
    sync_script:
      - bash sync
    build_script:
      - curl -o build https://raw.githubusercontent.com/qwry3657/cirrus/main/build
      - bash build
    upload_ccache_script: # Upload ccache to cloud foreground
      - curl -o upload_ccache https://raw.githubusercontent.com/qwry3657/cirrus/main/upload_ccache
      - bash upload_ccache # Ccache uploading script
